#
# Projekt: Jak na projekty v jazyce C
# Autor:   David Martinek
# Datum:   12.2.2009
#

# jméno programu
NAME=zaklady-03

# pøekladaè jazyka C
CC=gcc

# parametry pøekladaèe
CFLAGS=-std=c99 -Wall -pedantic -g

# pøídavné knihovny
#LIBS=-lm

$(NAME): $(NAME).c
	$(CC) $(CFLAGS) $(NAME).c -o $(NAME)
